#!/bin/sh
set -eu
umask 077
exec 9>/opt/taoai-shop/backup.lock
flock -n 9 || exit 0
TASK_ROOT=/opt/taoai-shop
TASK_STAMP=$(date -u +%Y%m%dT%H%M%SZ)
TASK_BACKUP="$TASK_ROOT/backups/$TASK_STAMP"
mkdir -p "$TASK_BACKUP"
docker exec taoai-shop-postgres pg_dump -U taoai_shop -d taoai_shop -Fc > "$TASK_BACKUP/database.dump"
test -s "$TASK_BACKUP/database.dump"
tar -czf "$TASK_BACKUP/config-and-uploads.tar.gz" -C "$TASK_ROOT" config.yml postgres.env redis.conf compose.yaml admin-access.json uploads deploy runtime/Dockerfile
sha256sum "$TASK_BACKUP/database.dump" "$TASK_BACKUP/config-and-uploads.tar.gz" > "$TASK_BACKUP/SHA256SUMS"
# Only prune dated backup folders generated by this script, after successful backup.
python3 - "$TASK_ROOT/backups" <<'PY'
from pathlib import Path
import re, shutil, sys
folders=sorted(p for p in Path(sys.argv[1]).iterdir() if p.is_dir() and re.fullmatch(r'\d{8}T\d{6}Z',p.name))
for p in folders[:-14]:shutil.rmtree(p)
PY
printf 'TaoAi backup complete: %s\n' "$TASK_STAMP"
